// NB: `.js` negli import
export { controllo_partita_iva } from './src/controllo-partita-iva-IT.js';
export { controllo_codice_fiscale } from './src/controllo-codice-fiscale-IT.js';
export { default as date_in_sequenza } from './src/date-in-sequenza.js';
export { isValidDate, minutesToHour, dateFromISO, dateStringToISO, formatDate, formatTime, formatDateTime } from './src/date-utilities.js';
export { obfuscate_email, email_antispam } from './src/email-antispam.js';
export { escapeHTML } from './src/escapeHTML.js';
export { default as festivita } from './src/festivita.js';
export { disableBtnsOnSubmit, throwErr, setFormElementValue, getFormElementValue } from './src/form-utilities.js';
export { default as genera_pwd } from './src/genera-pwd.js';
export { inputDateRawFallback } from './src/input-date-raw-fallback.js';
export { inputDateSupport, inputDatetimeSupport, inputTimeSupport } from './src/input-date-support.js';
export { jquery_loader } from './src/jquery-ondemand-loader.js';
export { mesi, mesi_0, giorni, giorni_0 } from './src/mesi-giorni-it.js';
export { overlay, remove_overlay } from './src/overlay.js';
export { print_icon } from './src/print-icon.js';
export { $, $$ } from './src/selector-utilities.js';
export { disposeSliding, slideUp, slideDown, slideToggle } from './src/slide-up-down-toggle.js';
export { better_text, title_case, sentence_case, text_cleaner } from './src/text-utilities.js';
export { textarea_autosize } from './src/textarea-autosize.js';
export { default as toggle_disabled } from './src/toggle-disabled.js';
export { default as toggle_required } from './src/toggle-required.js';
export { truncate_string } from './src/truncate-string.js';
export { default as unique_id } from './src/unique-id.js';
export { default as url_concat } from './src/url-concat.js';
export { webpSupport } from './src/webp-support.js';
